/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.0-RC1
 * Generated at: 2017-06-27 11:21:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.study.mvc.tools.PageManager;
import com.study.mvc.model.bean.StudentInfo;
import com.study.mvc.model.bean.UserInfo;

public final class UserList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005factionmessage_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fs_005factionmessage_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fs_005factionmessage_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- uri:标签库描述文件所在位置 -->\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>具体功能页面</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\tbody{\r\n");
      out.write("\t\tfont-size: 26px;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\" src=\"Myjs/jquery-1.7.2.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction delArm(){\r\n");
      out.write("\t\tif(confirm(\"确认要删除吗？\")){\r\n");
      out.write("\t\t\treturn true;\r\n");
      out.write("\t\t}\t\r\n");
      out.write("\t\telse{\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction pageNumberS(){\r\n");
      out.write("\t\treturn document.getElementById('pagenum').value;\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    function getBodyData(forword){\r\n");
      out.write("\t\t$.post(\r\n");
      out.write("\t\t\t\"getdata?page=\"+forword,\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tstuname:$(\"#stuname\").val()\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tfunction(data){\t\r\n");
      out.write("\t\t\t\t//将Json转换为Js数组对象\r\n");
      out.write("\t\t\t\tvar pageNum=data.maxpage;\r\n");
      out.write("\t\t\t\t/* alert(pageNum) */\r\n");
      out.write("\t\t\t\tvar students=eval(data.result);\r\n");
      out.write("\t\t\t\tvar htmStr=\"\";\r\n");
      out.write("\t\t\t\thtmStr+=\"<hr><table border=\\\"3\\\">\";\r\n");
      out.write("\t\t\t\thtmStr+=\"<caption>学员信息一览</caption>\";\r\n");
      out.write("\t\t\t\thtmStr+=\"<tr align='center'><td>序号</td><td>学号</td><td>姓名</td><td>性别</td><td>年龄</td><td>毕业院校</td><td colspan=\\\"2\\\">操作</td></tr>\";\r\n");
      out.write("\t\t\t\tif(students==null){\r\n");
      out.write("\t\t\t\t\thtmStr+=\"<tr align='center'>\";\r\n");
      out.write("\t\t\t\t\thtmStr+=\"<td colspan=\\\"8\\\" align=\\\"center\\\">没有符合条件的数据</td>\";\r\n");
      out.write("\t\t\t\t\thtmStr+=\"</tr>\";\r\n");
      out.write("\t\t\t\t\thtmStr+=\"</table>\";\r\n");
      out.write("\t\t\t\t\t$(\"#tbl\").html(htmStr);\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t//如何使用Jquery解析XML中的数据\r\n");
      out.write("\t\t\t\t//用Jquery方法each遍历该数组对象，尤其注意遍历规则函数的写法\r\n");
      out.write("\t\t\t\t$.each(students,function(i,stu){\r\n");
      out.write("\t\t\t\t\thtmStr+=\"<tr align='center'>\";\r\n");
      out.write("\t\t\t\t\thtmStr+=\"<td>\"+(i+1)+\"</td>\";\r\n");
      out.write("\t\t\t\t\thtmStr+=\"<td>\"+stu.id+\"</td>\";\r\n");
      out.write("\t\t\t\t\thtmStr+=\"<td>\"+stu.name+\"</td>\";\r\n");
      out.write("\t\t\t\t\thtmStr+=\"<td>\"+stu.sex+\"</td>\";\r\n");
      out.write("\t\t\t\t\thtmStr+=\"<td>\"+stu.age+\"</td>\";\r\n");
      out.write("\t\t\t\t\thtmStr+=\"<td>\"+stu.gradeFrom+\"</td>\";\r\n");
      out.write("\t\t\t\t\thtmStr+=\"<td><a href=\\\"modifyStu?id=\"+stu.id+\"\\\">修改</a></td>\";\r\n");
      out.write("\t\t\t\t\t/* 删除没搞定 */\r\n");
      out.write("\t\t\t\t\thtmStr+=\"<td><a href=\\\"delStu?id=\"+stu.id+\"\\\" onclick=\\\"return delArm()\\\">删除</a></td>\";\r\n");
      out.write("\t\t\t\t\thtmStr+=\"</tr>\";\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\thtmStr+=\"<tr align='center'>\";\r\n");
      out.write("\t\t\t\thtmStr+=\"<td colspan='2'><input type=\\\"button\\\" value='首页' onclick='getBodyData(\\\"first\\\")'></td>\";\r\n");
      out.write("\t\t\t\thtmStr+=\"<td><input type=\\\"button\\\" value='前页' onclick='getBodyData(\\\"pre\\\")'></td>\";\r\n");
      out.write("\t\t\t\thtmStr+=\"<td colspan='2'><input type=\\\"button\\\" value='次页' onclick='getBodyData(\\\"nxt\\\")'></td>\";\r\n");
      out.write("\t\t\t\thtmStr+=\"<td><input type=\\\"button\\\" value='尾页' onclick='getBodyData(\\\"last\\\")'></td>\";\r\n");
      out.write("\t\t\t\thtmStr+=\"<td colspan='2'><input type='number' id='pagenum'><input type=\\\"button\\\" value='指定页' onclick='getBodyData(pageNumberS())'></td>\";\r\n");
      out.write("\t\t\t\thtmStr+=\"</tr>\";\r\n");
      out.write("\t\t\t\tif(pageNum>1){\r\n");
      out.write("\t\t\t\t\thtmStr+=\"<tr align='center'>\";\r\n");
      out.write("\t\t\t\t\thtmStr+=\"<td colspan='8'>\"\r\n");
      out.write("\t\t\t\t\tfor(var i=1;i<=pageNum;i++){\r\n");
      out.write("\t\t\t\t\t\thtmStr+=\"<a href=\\\"#\\\" onclick=\\\"getBodyData(\"+i+\")\\\" style='margin-left:20px;'>\"+i+\"</a>\"\r\n");
      out.write("\t\t\t\t\t\tif(i%10==0){\r\n");
      out.write("\t\t\t\t\t\t\thtmStr+=\"<br>\";\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\thtmStr+=\"</td>\";\r\n");
      out.write("\t\t\t\t\thtmStr+=\"</tr>\";\r\n");
      out.write("\t\t\t\t } \r\n");
      out.write("\t\t\t\thtmStr+=\"</table>\";\r\n");
      out.write("\t\t\t\t//首页 前页 次页 尾页\r\n");
      out.write("\t\t\t\t$(\"#tbl\").html(htmStr);\t\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t\"JSON\"\r\n");
      out.write("\t\t);\r\n");
      out.write("    }\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t$(\"#search\").click(function(){\r\n");
      out.write("\t\t\tgetBodyData('first');\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t欢迎您，");
      if (_jspx_meth_s_005fproperty_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t<hr>\r\n");
      out.write("    <form action=\"\" >\r\n");
      out.write("\t\t<table border=\"3\">\r\n");
      out.write("\t\t    <caption>学员信息查询处理</caption>\r\n");
      out.write("\t\t    <tr>\r\n");
      out.write("\t\t       <td>姓名：</td><!--模糊查询-->\r\n");
      out.write("\t\t       <td><input type=\"text\" name=\"stuname\" id=\"stuname\" style=\"height:30px;\"></td>\r\n");
      out.write("\t\t    </tr>\r\n");
      out.write("\t\t    <tr>\r\n");
      out.write("\t\t       <td colspan=\"2\" style=\"text-align: center;\">\r\n");
      out.write("\t\t       \t\t<input type=\"button\" id=\"search\" value=\"查询\" style=\"height:30px;font-size: 20px;\">\r\n");
      out.write("\t\t       \t\t<input type=\"reset\" id=\"clear\" value=\"重置查询\" style=\"height:30px;font-size: 20px;margin-left: 20px;\">\r\n");
      out.write("\t\t       \t</td>\r\n");
      out.write("\t\t    </tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("    </form>\r\n");
      out.write("    <!-- Ajax需要刷新的区域 -->\r\n");
      out.write("    <div id=\"tbl\"></div>\r\n");
      out.write("    ");
      if (_jspx_meth_s_005factionmessage_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_s_005fproperty_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:property
    org.apache.struts2.views.jsp.PropertyTag _jspx_th_s_005fproperty_005f0 = (org.apache.struts2.views.jsp.PropertyTag) _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.get(org.apache.struts2.views.jsp.PropertyTag.class);
    _jspx_th_s_005fproperty_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005fproperty_005f0.setParent(null);
    // /UserList.jsp(106,5) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_s_005fproperty_005f0.setValue("#session.userInfo.name");
    int _jspx_eval_s_005fproperty_005f0 = _jspx_th_s_005fproperty_005f0.doStartTag();
    if (_jspx_th_s_005fproperty_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005fproperty_0026_005fvalue_005fnobody.reuse(_jspx_th_s_005fproperty_005f0);
    return false;
  }

  private boolean _jspx_meth_s_005factionmessage_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:actionmessage
    org.apache.struts2.views.jsp.ui.ActionMessageTag _jspx_th_s_005factionmessage_005f0 = (org.apache.struts2.views.jsp.ui.ActionMessageTag) _005fjspx_005ftagPool_005fs_005factionmessage_005fnobody.get(org.apache.struts2.views.jsp.ui.ActionMessageTag.class);
    _jspx_th_s_005factionmessage_005f0.setPageContext(_jspx_page_context);
    _jspx_th_s_005factionmessage_005f0.setParent(null);
    int _jspx_eval_s_005factionmessage_005f0 = _jspx_th_s_005factionmessage_005f0.doStartTag();
    if (_jspx_th_s_005factionmessage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fs_005factionmessage_005fnobody.reuse(_jspx_th_s_005factionmessage_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fs_005factionmessage_005fnobody.reuse(_jspx_th_s_005factionmessage_005f0);
    return false;
  }
}
